# Generated by Django 5.2.6 on 2025-09-13 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='educationprogram',
            name='teachers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_teacher': True}, related_name='teaching_programs', to=settings.AUTH_USER_MODEL, verbose_name='Прикрепленные преподаватели'),
        ),
        migrations.AddField(
            model_name='educationprogram',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='data.faculty', verbose_name='Факультет'),
        ),
        migrations.AddField(
            model_name='programaboutitem',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_items', to='data.educationprogram', verbose_name='Программа'),
        ),
        migrations.AddField(
            model_name='programmodule',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='data.educationprogram', verbose_name='Программа'),
        ),
        migrations.AddField(
            model_name='programmoduleitem',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='data.programmodule', verbose_name='Модуль'),
        ),
    ]
