# Generated by Django 5.2.6 on 2025-09-13 11:30

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_lectureformat_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmodule',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
