# Generated by Django 5.2.6 on 2025-09-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_programmodule_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationProgramTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='educationprogram',
            name='tags',
            field=models.ManyToManyField(blank=True, to='data.educationprogramtag'),
        ),
    ]
