# Generated by Django 5.2.6 on 2025-09-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_educationprogramtag_educationprogram_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationprogramtag',
            options={'verbose_name': 'Теги Программа обучения', 'verbose_name_plural': 'Теги Программа обучения'},
        ),
        migrations.AddField(
            model_name='programaboutitem',
            name='svg',
            field=models.TextField(blank=True, null=True, verbose_name='КОД SVG'),
        ),
        migrations.AlterField(
            model_name='educationprogram',
            name='tags',
            field=models.ManyToManyField(blank=True, to='data.educationprogramtag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='programaboutitem',
            name='block_type',
            field=models.CharField(choices=[('default', 'Белый'), ('primary', 'Красный'), ('dark', 'Темный')], max_length=10, verbose_name='Вид плашки'),
        ),
    ]
