# Generated by Django 5.2.6 on 2025-09-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_alter_educationprogramtag_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationprogram',
            name='is_online',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='educationprogram',
            name='study_plan',
            field=models.FileField(blank=True, null=True, upload_to='programs/study_plans/', verbose_name='План обучения'),
        ),
    ]
