# Generated by Django 5.2.6 on 2025-09-14 20:14

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_educationprogram_is_online_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок вывода')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.CharField(blank=True, max_length=255, null=True, verbose_name='ЧПУ')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='programs/backgrounds/', verbose_name='Фотография на задний фон')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='programs/covers/', verbose_name='Фотография обложка')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='Короткое описание')),
                ('duration', models.CharField(blank=True, max_length=255, null=True, verbose_name='Срок обучения (текстовое)')),
                ('price', models.CharField(blank=True, max_length=255, null=True, verbose_name='Стоимость (текстовое)')),
                ('start_date', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата начала (текстовое)')),
                ('end_date', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата окончания (текстовое)')),
                ('video', models.FileField(blank=True, null=True, upload_to='programs/videos/', verbose_name='Видео файл')),
                ('video_text', models.TextField(blank=True, null=True, verbose_name='Текст на видео блок')),
                ('study_plan', models.FileField(blank=True, null=True, upload_to='programs/study_plans/', verbose_name='План обучения')),
                ('format', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.lectureformat', verbose_name='Формат ')),
                ('teachers', models.ManyToManyField(blank=True, limit_choices_to={'is_teacher': True}, related_name='teachers', to=settings.AUTH_USER_MODEL, verbose_name='Прикрепленные преподаватели')),
            ],
            options={
                'verbose_name': 'Лекция',
                'verbose_name_plural': 'Лекции',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LectureAboutItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('svg', models.TextField(blank=True, null=True, verbose_name='КОД SVG')),
                ('text', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Текст')),
                ('block_type', models.CharField(choices=[('default', 'Белый'), ('primary', 'Красный'), ('dark', 'Темный')], max_length=10, verbose_name='Вид плашки')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок вывода')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_items', to='data.lecture', verbose_name='Лекция')),
            ],
            options={
                'verbose_name': "Пункт 'Результат обучения'",
                'verbose_name_plural': "Пункты 'Результат обучения'",
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LectureForItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('svg', models.TextField(blank=True, null=True, verbose_name='КОД SVG')),
                ('text', models.TextField(verbose_name='Текст')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок вывода')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='for_items', to='data.lecture', verbose_name='Программа')),
            ],
            options={
                'verbose_name': "Пункт 'Для кого'",
                'verbose_name_plural': "Пункты 'Для кого'",
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LectureModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок вывода')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание')),
                ('files', models.FileField(blank=True, null=True, upload_to='programs/modules/files/', verbose_name='Файлы')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_modules', to='data.educationprogram', verbose_name='Программа')),
            ],
            options={
                'verbose_name': 'Модуль обучения',
                'verbose_name_plural': 'Модули обучения',
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='ProgramModuleItem',
        ),
    ]
