# Generated by Django 5.2.6 on 2025-09-14 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_lecture_lectureaboutitem_lectureforitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturemodule',
            name='program',
        ),
        migrations.AddField(
            model_name='lecturemodule',
            name='lecture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecture_modules', to='data.lecture', verbose_name='Программа'),
        ),
    ]
