# Generated by Django 5.2.6 on 2025-09-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_remove_lecturemodule_program_lecturemodule_lecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='access',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Доступ'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='date',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата проведения'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='format_txt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Формат(текст)'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='learn_time',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Нагрузка'),
        ),
    ]
