# Generated by Django 5.2.6 on 2025-09-15 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_newstag_newsitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newstag',
            options={'ordering': ('order_num',), 'verbose_name': 'Тег новости', 'verbose_name_plural': 'Теги новостей'},
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='creator',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_teacher': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
