# Generated by Django 5.2.6 on 2025-09-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_alter_newstag_options_alter_newsitem_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.IntegerField(default=1, null=True)),
                ('top_image', models.ImageField(blank=True, null=True, upload_to='parnert/images/', verbose_name='Фотография')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='Автор')),
                ('text1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подпись')),
                ('show_on_main', models.BooleanField(default=True, verbose_name='Показывать на главной')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
                'ordering': ('order_num',),
            },
        ),
    ]
