# Generated by Django 5.2.6 on 2025-09-17 12:08

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок вывода')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('price_text', models.CharField(max_length=255, verbose_name='Цена описание')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='lecturemodule',
            name='lecture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecture_modules', to='data.lecture', verbose_name='Лекция'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.lecturetariff', verbose_name='Тариф'),
        ),
        migrations.CreateModel(
            name='LectureTariffItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Текст')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок вывода')),
                ('lecture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tariff_items', to='data.lecturetariff', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Тариф пункты',
                'verbose_name_plural': 'Тариф пункты',
                'ordering': ['order'],
            },
        ),
    ]
