# Generated by Django 5.2.6 on 2025-09-22 07:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_lecturetariff_alter_lecturemodule_lecture_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('text1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подпись')),
                ('date', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка')),
                ('teachers', models.ManyToManyField(limit_choices_to={'is_teacher': True}, related_name='publications', to=settings.AUTH_USER_MODEL, verbose_name='Относится к  преподаватели')),
            ],
            options={
                'verbose_name': 'Научные публикации',
                'verbose_name_plural': 'Научные публикации',
            },
        ),
    ]
