# Generated by Django 5.2.6 on 2025-09-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_publication'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.TextField(blank=True, null=True, verbose_name='ФИО')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ваш email')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон')),
                ('page', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название лектория\\программы')),
            ],
            options={
                'verbose_name': 'форма заявки со страницы лектория\\программы ',
                'verbose_name_plural': 'форма заявки со страницы лектория\\программы ',
            },
        ),
        migrations.CreateModel(
            name='QuestionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.TextField(blank=True, null=True, verbose_name='ФИО')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ваш email')),
                ('text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'вопросная форма',
                'verbose_name_plural': 'вопросная форма)',
            },
        ),
    ]
