# Generated by Django 5.2.6 on 2025-09-29 18:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_lectionform_questionform'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='teachers',
            field=models.ManyToManyField(related_name='publications', to=settings.AUTH_USER_MODEL, verbose_name='Относится к  преподаватели'),
        ),
    ]
