# Generated by Django 5.2.6 on 2025-10-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_alter_publication_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationprogram',
            name='video_url',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка на видео'),
        ),
    ]
