# Generated by Django 5.2.6 on 2025-10-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_educationprogram_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationprogram',
            name='quote_text',
            field=models.TextField(blank=True, null=True, verbose_name='Цитата'),
        ),
    ]
