# Generated by Django 5.2.6 on 2025-10-05 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_educationprogram_quote_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('svg', models.TextField(blank=True, null=True, verbose_name='КОД SVG')),
                ('text', models.TextField(verbose_name='Описание')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_features', to='data.educationprogram', verbose_name='Программа')),
            ],
            options={
                'verbose_name': 'Пункт преимущества',
                'verbose_name_plural': 'преимущества',
            },
        ),
        migrations.CreateModel(
            name='ProgramForItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255, verbose_name='Тег')),
                ('name', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Описание')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_for_items', to='data.educationprogram', verbose_name='Программа')),
            ],
            options={
                'verbose_name': "Пункт 'Для кого'",
                'verbose_name_plural': "Пункты 'Для кого'",
            },
        ),
    ]
