# Generated by Django 5.2.6 on 2025-10-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_programfeature_programforitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programfeature',
            name='svg',
        ),
        migrations.RemoveField(
            model_name='programforitem',
            name='tag',
        ),
        migrations.AddField(
            model_name='programfeature',
            name='tag',
            field=models.CharField(max_length=255, null=True, verbose_name='Тег'),
        ),
        migrations.AddField(
            model_name='programforitem',
            name='svg',
            field=models.TextField(blank=True, null=True, verbose_name='КОД SVG'),
        ),
    ]
