# Generated by Django 5.2.6 on 2025-10-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_remove_programfeature_svg_remove_programforitem_tag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programforitem',
            name='svg',
        ),
        migrations.AddField(
            model_name='programforitem',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='programs/study_for_item/', verbose_name='Картинка'),
        ),
    ]
