# Generated by Django 5.2.6 on 2025-10-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_remove_programforitem_svg_programforitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationprogram',
            name='attestat_label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Последнее поле текст'),
        ),
        migrations.AddField(
            model_name='educationprogram',
            name='attestat_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Последнее поле заголовок'),
        ),
    ]
