# Generated by Django 5.2.6 on 2025-10-07 08:07

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_educationprogram_attestat_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationprogram',
            name='video_text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Текст на видео блок'),
        ),
    ]
