# Generated by Django 5.2.6 on 2025-10-11 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0024_alter_educationprogram_video_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationprogram',
            name='caiere_tag',
            field=models.TextField(blank=True, null=True, verbose_name='Блок Карьера тег'),
        ),
        migrations.AddField(
            model_name='educationprogram',
            name='caiere_text',
            field=models.TextField(blank=True, null=True, verbose_name='Блок Карьера текст'),
        ),
        migrations.AddField(
            model_name='educationprogram',
            name='caiere_title',
            field=models.TextField(blank=True, null=True, verbose_name='Блок Карьера заголовок'),
        ),
        migrations.CreateModel(
            name='ProgramCaiereItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('default', 'Белый'), ('primary', 'Красный'), ('dark', 'Темный')], max_length=10, verbose_name='Вид плашки')),
                ('text', models.TextField(verbose_name='Описание')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caiere_items', to='data.educationprogram', verbose_name='Программа')),
            ],
            options={
                'verbose_name': "Пункт 'Блок Карьера'",
                'verbose_name_plural': "Пункты 'Блок Карьера'",
            },
        ),
    ]
