# Generated by Django 5.2.6 on 2025-10-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0025_educationprogram_caiere_tag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='start_date',
        ),
        migrations.AddField(
            model_name='educationprogram',
            name='page_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='educationprogram',
            name='page_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='card_tag',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег на карточке'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='page_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='page_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='video_url',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка на видео'),
        ),
        migrations.AddField(
            model_name='lecturemodule',
            name='tag',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='page_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='page_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='programmodule',
            name='tag',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег'),
        ),
    ]
