# Generated by Django 5.2.6 on 2025-10-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0026_remove_lecture_end_date_remove_lecture_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationprogram',
            name='page_description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='page_description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='page_description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
