# Generated by Django 5.2.6 on 2025-10-13 14:28

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0027_alter_educationprogram_page_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationprogram',
            name='video_image',
            field=models.FileField(blank=True, null=True, upload_to='programs/videos/', verbose_name='Видео картинка'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='video_image',
            field=models.FileField(blank=True, null=True, upload_to='programs/videos/', verbose_name='Видео картинка'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='video_text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Текст на видео блок'),
        ),
    ]
