# Generated by Django 5.2.6 on 2025-10-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0028_educationprogram_video_image_lecture_video_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lectureforitem',
            name='svg',
        ),
        migrations.AddField(
            model_name='lectureforitem',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='lecture/study_for_item/', verbose_name='Картинка'),
        ),
    ]
