# Generated by Django 5.2.6 on 2025-10-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0029_remove_lectureforitem_svg_lectureforitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectionform',
            name='fio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='questionform',
            name='fio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='questionform',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
    ]
