# Generated by Django 5.2.6 on 2025-10-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0030_alter_lectionform_fio_alter_questionform_fio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionform',
            name='page',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Страница'),
        ),
    ]
