# Generated by Django 5.2.6 on 2025-10-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0031_questionform_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectionform',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='questionform',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
