# Generated by Django 5.2.6 on 2025-09-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='quality',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Квалификация'),
        ),
        migrations.AddField(
            model_name='user',
            name='work_time',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Стаж работы'),
        ),
        migrations.AddField(
            model_name='user',
            name='tags',
            field=models.ManyToManyField(blank=True, to='user.usertag'),
        ),
    ]
