# Generated by Django 5.2.6 on 2025-09-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usertag_user_quality_user_work_time_user_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ЧПУ'),
        ),
    ]
