# Generated by Django 5.2.6 on 2025-10-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_at_index',
            field=models.BooleanField(default=False, verbose_name='Показывать на главной'),
        ),
    ]
